version: '3'
# # INFO
# All $VARIABLES are currently stored in a .env file on the same level as this
# document, please remember to populate it.
#
# You can test to see if the variables are loading correctly with the command:
# * `docker compose config`
# If the variables still have a $ on them then the .env is not being loaded.

# # USAGE
# The reccomended commands when working with docker compose is to use:
# * `docker compose up --build -d`
# This will force any container with changes to rebuild
#
# The reccomended way to take down the containers is with:
# * `docker compose down -v`
# This will ensure that the volume is deleted too.

# # Deployment
# The images are stored on docker hub. The deployment flow is as follows:
# 1. Login into Docker with `docker login -u omnihost` and the access token
# 2. Build the images with `docker compose build`
# 3. Push the images with `docker compose push`
# 4. On the deployment machine, Login into Docker with `docker login -u omnihost` and the access token
# 5. On the deployment machine, pull the images with `docker compose pull`
# 6. On the deployment machine, run the images with `docker compose up -d`
# 6.B On the deployment machine, run the Caddy reverse proxy if it isn't already running with `docker compose -f docker-compose.caddy.yml up --build -d`

services:
  api:
    container_name: omnihost-api
    image: omnihost/dangleterre:api-${DEPLOYMENT_ENV:-local}
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./.deploy/api/Dockerfile
    environment:
      API_LINODE_PERSONAL_TOKEN: ${API_LINODE_PERSONAL_TOKEN}
      API_LINODE_STORAGE_CLUSTER_ID: ${API_LINODE_STORAGE_CLUSTER_ID}
      API_LINODE_STORAGE_BUCKET_ID: ${API_LINODE_STORAGE_BUCKET_ID}
      API_LINODE_STORAGE_ACCESS_KEY: ${API_LINODE_STORAGE_ACCESS_KEY}
      API_LINODE_STORAGE_SECRET_KEY: ${API_LINODE_STORAGE_SECRET_KEY}
      API_POSTGRES_HOST: ${API_POSTGRES_HOST:-omnihost-postgres}
      API_POSTGRES_PORT: ${API_POSTGRES_PORT:-5432}
      API_POSTGRES_USER: ${API_POSTGRES_USER:-root}
      API_POSTGRES_PASSWORD: ${API_POSTGRES_PASSWORD:-root}
      API_POSTGRES_DATABASE: ${API_POSTGRES_DATABASE:-omnihost}
      API_GLOBAL_CORS_ALLOWED_ORIGIN: ${API_GLOBAL_CORS_ALLOWED_ORIGIN}
      API_JWT_SECRET: ${API_JWT_SECRET}
      API_MANAGER_PASSWORD: ${API_MANAGER_PASSWORD:-'abcDEF123'}
      API_SENDGRID_API_KEY: ${API_SENDGRID_API_KEY:-''}
      API_SENTRY_DSN: ${API_SENTRY_DSN:-''}
      API_SENTRY_TRACING_SAMPLE_RATE: ${API_SENTRY_TRACING_SAMPLE_RATE:-1.0}
      API_ENVIRONMENT: ${API_ENVIRONMENT:-DEVELOPMENT}
    networks:
      - omnihost-net
    ports:
      - 3333:3333

  frontend:
    container_name: omnihost-frontend
    image: omnihost/dangleterre:frontend-${DEPLOYMENT_ENV:-local}
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./.deploy/frontend/Dockerfile
    environment:
      FRONTEND_API_URL: ${FRONTEND_API_URL:-http://localhost:3333}
      FRONTEND_SENTRY_DSN: ${FRONTEND_SENTRY_DSN:-''}
      FRONTEND_SENTRY_TRACING_SAMPLE_RATE: ${FRONTEND_SENTRY_TRACING_SAMPLE_RATE:-1.0}
      FRONTEND_SENTRY_TUNNEL: ${FRONTEND_SENTRY_TUNNEL}
      FRONTEND_ENVIRONMENT: ${FRONTEND_ENVIRONMENT:-DEVELOPMENT}
    networks:
      - omnihost-net
    ports:
      - 8080:80

  postgres:
    container_name: omnihost-postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${API_POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${API_POSTGRES_PASSWORD:-root}
      POSTGRES_DB: ${API_POSTGRES_DATABASE:-omnihost}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - ${API_POSTGRES_PORT:-5432}:5432
    networks:
      - omnihost-net

  sentry-tunnel:
    container_name: omnihost-sentry-tunnel
    image: omnihost/dangleterre:tunnel-${DEPLOYMENT_ENV:-local}
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./.deploy/sentry-tunnel/Dockerfile
    environment:
      TUNNEL_ALLOWED_DSNs: ${TUNNEL_ALLOWED_DSNs}
      TUNNEL_CORS_ALLOWED_ORIGINS: ${TUNNEL_CORS_ALLOWED_ORIGINS}
      TUNNEL_PORT: 5000
    networks:
      - omnihost-net
    ports:
      - 5000:5000

# ---------------------------------
# ------------ NETWORK ------------
networks:
  omnihost-net:
    name: omnihost-net

volumes:
  postgres:
