# Validate code for potential errors
# Triggered on pull requests
name: Lint CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install and lint the codebase
        run: |
          npm ci
          npm run lint
